### ISSUE TITLE
Feature request: Matplotlib toolbox

### ISSUE THREAD

**Issue by jo-mueller** [dstansby/napari-matplotlib#20]
It would be nice to have the typical matplotlib toolbar on top of the Figure Canvas. 

I think it could be added relatively easily in the definition of the MPL Widget by adding

```Python
self.toolbar = NavigationToolbar(self.canvas, self)
```

to the layout. I could send you a PR to implement this - let me know if I should.

**Comment by dstansby** [comment]
Yes, please do, PRs very welcome!
